[versions]
accompanist = "0.28.0"
androidGradle = "7.4.1"
androidxActivity = "1.6.1"
androidBilling = "5.1.0"
androidxCore = "1.9.0"
androidxEspresso = "3.5.1"
androidxLifecycle = "2.5.1"
androidxTestCore = "1.5.0"
androidxTestJunit = "1.1.5"
arrow = "1.1.5"
coil = "1.4.0"
compose = "1.4.0-beta01"
composeCompiler = "1.4.0"
constraintLayout = "1.0.1"
crashlytics = "2.9.4"
dataStore = "1.0.0"
detekt = "1.22.0"
detektTwitterCompose = "0.0.26"
firebase = "31.2.1"
geohash = "1.4.0"
glance = "1.0.0-SNAPSHOT"
gms = "4.3.15"
junit = "4.13.2"
kermit = "1.2.2"
klock = "3.4.0"
koin = "3.3.2"
koinCompose = "3.4.1"
koinKsp = "1.1.1"
kotlin = "1.8.0"
kotlinCoroutines = "1.6.4"
kotlinImmutableCollections = "0.3.3"
kotlinSerialization = "1.4.1"
ksp = "1.8.0-1.0.8"
mockk = "1.13.4"
material3 = "1.1.0-alpha06"
navigation = "2.5.3"
playServices = "21.0.1"
sqlDelight = "1.5.5"
turbine = "0.12.1"
workManager = "2.8.0"

[libraries]
# region Gradle
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
gradle-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-gms = { module = "com.google.gms:google-services", version.ref = "gms" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
gradle-shuttle-android = { module = "shuttle.plugins.android:android" }
gradle-shuttle-detekt = { module = "shuttle.plugins.detekt:detekt" }
gradle-shuttle-modulesCatalog = { module = "shuttle.plugins.modules-catalog:modules-catalog" }
gradle-sqlDelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqlDelight" }
# endregion

ksp-arrow = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

android-billing = { module = "com.android.billingclient:billing-ktx", version.ref = "androidBilling" }

androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-dataStore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
androidx-glance = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxTestJunit" }
androidx-workManager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
androidx-workManager-test = { module = "androidx.work:work-testing", version.ref = "workManager" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

compose-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayout"}
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-uiTest-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-rules-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-rules-twitter-compose = { module = "com.twitter.compose.rules:detekt", version.ref = "detektTwitterCompose" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }

geohash = { module = "ch.hsr:geohash", version.ref = "geohash" }

junit = { module = "junit:junit", version.ref = "junit" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

klock = { module = "com.soywiz.korlibs.klock:klock", version.ref = "klock" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinCompose" }
koin-android-workManager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinKsp" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinKsp" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }

kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinImmutableCollections" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }

material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

playServices-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServices" }

sqlDelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-coroutines = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-sqlite = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
base = [
    "arrow-core",
    "arrow-optics",
    "kermit",
    "koin-annotations",
    "koin-core",
    "kotlin-coroutines"
]
compose = [
    "coil-compose",
    "compose-constraintLayout",
    "compose-ui",
    "compose-uiToolingPreview",
    "koin-android-compose",
    "kotlin-immutable-collections",
    "material3"
]
compose-debug = [
    "compose-uiTest-manifest",
    "compose-uiTooling"
]
test-android = [
    "androidx-test-core",
    "androidx-test-junit",
    "androidx-test-espresso",
    "koin-test",
    "koin-test-junit4",
    "mockk-android"
]
test-kotlin = [
    "kotlin-coroutines-test",
    "kotlin-test-junit",
    "mockk",
    "turbine"
]

